import os
os.system("cls")
print("dir")
print("************")
os.system("dir")
print("mkdir testdir")
print("**************")
os.system("pause")
print("rmdir testdir")
print("**************")
os.system("rmdir testdir")
print("dir testdir")
print("***************")
os.system("dir testdir")